language: java
sudo: required
services:
  - couchdb
  - mysql
install:
  - echo "skip" # or anything that returns 0 status.
  - sudo updatedb #Giving couchdb time to start.
  - sudo netstat -tuplen # listing all the port for debug purpose.
before_script:
  - curl -X PUT http://localhost:5984/_config/admins/rootuser -d '"adminpass"'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('VA1913wm') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root 
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean compile
notifications:
  slack:
    secure: Ueku2w/RdSfh1zEDErTbHi+hRx154fH10ykGcfrXPXhTVtWopG73BGDRKfVgU1MCokEo+2jtkRAuJB29R1PV8E3845wWJFs9ZPGcl0rjfx3qP2G/bCuARRHmBJ33YStROvaVF3ppNjJau7VinIF3giem+4WgtQ8KPmqqviDg8Tw=
after_success:
  - mvn  jacoco:report coveralls:report
  - bash <(curl -s https://codecov.io/bash) 
